// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaBzDOE2-MJSaQysCX49W-vewF3C4w75c',
    appId: '1:207256468674:web:9589940476c8ea1b97cf5b',
    messagingSenderId: '207256468674',
    projectId: 'ecommerceapp-fe2ec',
    authDomain: 'ecommerceapp-fe2ec.firebaseapp.com',
    storageBucket: 'ecommerceapp-fe2ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_JfA0Fq5C79oSxh_lXrc_7hpUp4lq1DY',
    appId: '1:207256468674:android:37945eeb97fb614297cf5b',
    messagingSenderId: '207256468674',
    projectId: 'ecommerceapp-fe2ec',
    storageBucket: 'ecommerceapp-fe2ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADaULBS9tRfcJPDK5n__-b_233nkDJn78',
    appId: '1:207256468674:ios:6e57d10bbf5b997d97cf5b',
    messagingSenderId: '207256468674',
    projectId: 'ecommerceapp-fe2ec',
    storageBucket: 'ecommerceapp-fe2ec.firebasestorage.app',
    androidClientId: '207256468674-h7e76h3vjqtuviv9ru4qgdbsft5hkvtv.apps.googleusercontent.com',
    iosClientId: '207256468674-bmcjmdperkq9oh7pgr1m5ebocl86pikl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaBzDOE2-MJSaQysCX49W-vewF3C4w75c',
    appId: '1:207256468674:web:4d956f90f782041c97cf5b',
    messagingSenderId: '207256468674',
    projectId: 'ecommerceapp-fe2ec',
    authDomain: 'ecommerceapp-fe2ec.firebaseapp.com',
    storageBucket: 'ecommerceapp-fe2ec.firebasestorage.app',
  );

}